[package]
name = "postgres-ffi"
version = "0.0.1"
edition = "2018"
build = "build.rs"

[lib]
name = "postgres_ffi"
crate-type = ["cdylib"]

[dependencies]
postgres = "0.15"

[build-dependencies]
cbindgen = "0.12"
